# Generated by Django 5.2.13 on 2026-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=20),
        ),
    ]
